name: lpr
channels:
  - defaults
dependencies:
  - python=3.10.13
  - pip:
      - flask==3.0.0
      - flask-restful==0.3.10
      - numpy==1.26.1
      - opencv-python==4.8.1.78
      - opencv-python-headless==4.8.0.74
      - pillow==10.1.0
      - scikit-learn==1.2.2
      - torch==2.1.0
      - torchvision==0.16.0
      - ultralytics==8.0.202
      - werkzeug==3.0.1
      - easydict==1.11
      - pymongo==4.6.0
      - requests==2.31.0
      - firebase-admin==6.2.0
      - paddleocr==2.0.1
